import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <Link to="/">
          <Button variant="ghost" className="mb-8">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="prose prose-slate dark:prose-invert max-w-none"
        >
          <h1 className="text-4xl font-bold mb-2">Terms and Conditions</h1>
          <p className="text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString('en-AU')}</p>

          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using MiraiPrep ("the Service"), you accept and agree to be bound by these Terms and Conditions. 
                If you do not agree to these terms, you must not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Service Description</h2>
              <p>
                MiraiPrep is an AI-powered interview preparation platform that provides:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Simulated technical and behavioral interviews</li>
                <li>AI-generated interview questions and feedback</li>
                <li>Practice sessions with real-time evaluation</li>
                <li>Performance analytics and recommendations</li>
              </ul>
              <p className="mt-4">
                The Service uses artificial intelligence technologies, including but not limited to OpenAI's GPT models, 
                Whisper (speech-to-text), and text-to-speech services. The Service is provided "as is" and we do not 
                guarantee specific outcomes or interview success.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. User Obligations</h2>
              <p>You agree to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Provide accurate and complete information when registering</li>
                <li>Maintain the security of your account credentials</li>
                <li>Use the Service only for lawful purposes</li>
                <li>Not attempt to reverse engineer, decompile, or extract source code</li>
                <li>Not use the Service to generate harmful, offensive, or illegal content</li>
                <li>Not share your account with others</li>
                <li>Comply with all applicable laws and regulations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. AI-Generated Content Disclaimer</h2>
              <p>
                <strong>Important:</strong> All interview questions, feedback, evaluations, and responses generated by the Service 
                are created using artificial intelligence and are for educational and practice purposes only.
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>AI-generated content may contain errors, inaccuracies, or biases</li>
                <li>Feedback and evaluations are not professional assessments</li>
                <li>The Service does not guarantee that practice questions will appear in actual interviews</li>
                <li>You should not rely solely on AI-generated content for career decisions</li>
                <li>We are not responsible for any consequences arising from your use of AI-generated content</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by Australian Consumer Law and other applicable laws:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>
                  <strong>No Guarantee of Results:</strong> We do not guarantee that using the Service will result in 
                  interview success, job offers, or career advancement.
                </li>
                <li>
                  <strong>Service Availability:</strong> We do not guarantee uninterrupted or error-free access to the Service. 
                  The Service may be unavailable due to maintenance, technical issues, or circumstances beyond our control.
                </li>
                <li>
                  <strong>Third-Party Services:</strong> The Service relies on third-party AI providers (including OpenAI). 
                  We are not responsible for the availability, accuracy, or performance of third-party services.
                </li>
                <li>
                  <strong>Exclusion of Consequential Damages:</strong> To the extent permitted by law, we exclude all liability 
                  for indirect, consequential, special, or punitive damages, including loss of profits, data, or opportunities.
                </li>
                <li>
                  <strong>Maximum Liability:</strong> Our total liability for any claims arising from or related to the Service 
                  shall not exceed the amount you paid to us in the 12 months preceding the claim, or AUD $100, whichever is greater.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Australian Consumer Law</h2>
              <p>
                Our goods and services come with guarantees that cannot be excluded under the Australian Consumer Law. 
                You are entitled to a replacement or refund for a major failure and compensation for any other reasonably 
                foreseeable loss or damage.
              </p>
              <p className="mt-4">
                Nothing in these Terms excludes, restricts, or modifies any rights you may have under the Australian Consumer Law 
                or any other applicable law that cannot be excluded, restricted, or modified.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. Intellectual Property</h2>
              <p>
                All content, features, and functionality of the Service, including but not limited to text, graphics, logos, 
                software, and AI-generated content, are owned by MiraiPrep or its licensors and are protected by Australian 
                and international copyright, trademark, and other intellectual property laws.
              </p>
              <p className="mt-4">
                You are granted a limited, non-exclusive, non-transferable license to access and use the Service for personal, 
                non-commercial purposes. You may not reproduce, distribute, modify, or create derivative works without our 
                express written permission.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Privacy and Data Protection</h2>
              <p>
                Your use of the Service is also governed by our Privacy Policy, which complies with the Australian Privacy 
                Principles (APPs) under the Privacy Act 1988 (Cth). By using the Service, you consent to the collection, 
                use, and disclosure of your personal information as described in our Privacy Policy.
              </p>
              <p className="mt-4">
                We collect and process your interview responses, performance data, and usage information to provide and improve 
                the Service. This data may be stored on servers located in Australia and other jurisdictions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Account Termination</h2>
              <p>We reserve the right to:</p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>Suspend or terminate your account if you breach these Terms</li>
                <li>Remove or modify content that violates our policies</li>
                <li>Discontinue or modify the Service at any time</li>
                <li>Refuse service to anyone for any reason</li>
              </ul>
              <p className="mt-4">
                You may terminate your account at any time by contacting us or using account deletion features. 
                Upon termination, your right to use the Service will immediately cease.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">10. Payment and Refunds</h2>
              <p>
                If you purchase a paid subscription:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>All fees are in Australian Dollars (AUD) unless otherwise stated</li>
                <li>Subscriptions automatically renew unless cancelled</li>
                <li>Refunds are provided in accordance with Australian Consumer Law</li>
                <li>We reserve the right to change pricing with 30 days' notice</li>
                <li>You may cancel your subscription at any time</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">11. Dispute Resolution</h2>
              <p>
                If you have a complaint or dispute regarding the Service:
              </p>
              <ol className="list-decimal pl-6 space-y-2 mt-4">
                <li>Contact us first to attempt to resolve the matter</li>
                <li>If unresolved, you may refer the matter to the Australian Competition and Consumer Commission (ACCC) or your local consumer protection agency</li>
                <li>These Terms are governed by the laws of Australia and the State of New South Wales</li>
                <li>Any legal proceedings must be commenced in the courts of New South Wales, Australia</li>
              </ol>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">12. Indemnification</h2>
              <p>
                You agree to indemnify, defend, and hold harmless MiraiPrep, its officers, directors, employees, and agents 
                from and against any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>Your use or misuse of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any rights of another party</li>
                <li>Any content you submit or transmit through the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">13. Modifications to Terms</h2>
              <p>
                We reserve the right to modify these Terms at any time. Material changes will be notified via email or 
                prominent notice on the Service. Your continued use of the Service after such modifications constitutes 
                acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">14. Severability</h2>
              <p>
                If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions 
                shall continue in full force and effect.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">15. Contact Information</h2>
              <p>
                If you have questions about these Terms, please contact us at:
              </p>
              <p className="mt-4">
                <strong>Email:</strong> support@miraiprep.com<br />
                <strong>Website:</strong> miraiprep.com
              </p>
            </section>

            <div className="mt-12 p-6 bg-muted rounded-lg border border-border">
              <p className="text-sm text-muted-foreground">
                <strong>Note:</strong> These Terms and Conditions are provided for informational purposes. 
                This is not legal advice. We recommend consulting with a qualified Australian lawyer to ensure 
                these terms meet your specific legal requirements and comply with all applicable Australian laws.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
